---
Amazon:
  accessKey: <YOUR ACCESS KEY>
  secretKey: <YOUR SECRET KEY>
  host: webservices.amazon.fr
  region: eu-west-1
  partnerTag: <YOUR PARTNER TAG>
  partnerType: Associates
  marketplace: www.amazon.fr
  condition: New

Server:
  port: 8080
  debug: true
  path: /amazon
  cors: false
  projectDir: <PATH WHERE THE PROJECT IS INSTALLED>
  httpCache: 3600

Redis:
  enabled: false
  host: localhost
  port: 6379
  password:
  username:
  expire: 3600
